# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-qw1rG-UrV0yplY97fXP10pX5HH6vtSE
"""

# KURULUM
!pip install groq gradio pillow requests huggingface_hub

#Kullanıcı Cümlesi
#        ↓
#Türkçe Hikâye Üretimi (LLM)
#        ↓
#Karakter Föyü + Sahne Ayıklama
#        ↓
#Her Sahne İçin Görsel Prompt
#        ↓
#AI Görsel Üretimi
#        ↓
#Web Arayüzünde Kitap Görünümü

# IMPORTLAR VE API ANAHTARLARI
import re
import io
import base64
import requests
from PIL import Image

import gradio as gr
from groq import Groq
from huggingface_hub import InferenceClient


GROQ_API_KEY = "**"
HF_TOKEN = "**"

groq_client = Groq(api_key=GROQ_API_KEY)

# HuggingFace FLUX (Görsel üretim)
HF_IMAGE_MODEL = "black-forest-labs/FLUX.1-schnell"
hf_image = InferenceClient(HF_IMAGE_MODEL, token=HF_TOKEN)

# HİKÂYE ÜRETİM PROMPTU
# Bu prompt LLM çıktısının formatını kontrol eder.
# Amaç:
# - Tamamı Türkçe
# - Uzun hikâye
# - Karakter föyü
# - Sahne listesi


STORY_SYSTEM_PROMPT = """
You are a professional children's storyteller with strict formatting rules.

IMPORTANT LANGUAGE RULE:
Even though the instructions are in English,
YOU MUST WRITE EVERYTHING IN NATURAL, FLUENT TURKISH.

Your task:
Turn the user's short sentence into:
• A long, emotional, 8–15 paragraph Turkish children's story
• A Turkish character sheet: “KARAKTER FÖYÜ”
• A Turkish scene list: “SAHNE BÖLÜMLERİ” (2-3 sentences each)

OUTPUT FORMAT (MUST MATCH EXACTLY):

HİKÂYE:
[uzun Türkçe hikâye]

KARAKTER FÖYÜ:
[fiziksel özellikler, kıyafetler, kişilik]

SAHNE BÖLÜMLERİ:
1) [Sahne]
2) [Sahne]
3) ...

IMPORTANT:
• All output must be in Turkish.
• No English inside the story.
"""

def generate_story(sentence: str, n_scenes: int) -> str:
    """
    Groq üzerinden LLaMA 3.3 70B ile Türkçe hikâye üretir.
    """
    response = groq_client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": STORY_SYSTEM_PROMPT},
            {"role": "user", "content": f"Başlangıç cümlesi: {sentence}\nSahne sayısı: {n_scenes}"}
        ],
        temperature=0.7,
        max_tokens=4000,
    )
    return response.choices[0].message.content


# SAHNE VE KARAKTER AYIKLAMA
# Model çıktısını ham metin olarak bırakmak yerine
# otomatik olarak sahne ve karakter bilgilerini ayrılır.

def extract_scenes(text: str):
    scenes = []
    for i, line in enumerate(text.splitlines()):
        line = line.strip()
        if re.match(r"^\d+\)\s+", line):
            scenes.append(line.split(")", 1)[1].strip())  # "1) ..." → metni al
    return scenes

def extract_character_sheet(text: str):
    parts = re.split(r"KARAKTER FÖYÜ\s*:", text, flags=re.IGNORECASE)
    if len(parts) < 2:
        return ""
    after = parts[1]
    before_scene = re.split(r"SAHNE BÖLÜMLERİ", after, flags=re.IGNORECASE)[0]
    return before_scene.strip()

# GÖRSEL PROMPT ÜRETİMİ
# Türkçe sahne + Türkçe karakter bilgisi
# İngilizce görsel prompt'a dönüştürülür.
# Çünkü görsel modeller İngilizce promptlarda daha stabildir.

VISUAL_SYSTEM_PROMPT = """
You are a senior visual prompt engineer for children's books.

TASK:
Convert a TURKISH scene + character sheet into ONE English visual prompt.

RULES:
- Respect character appearance exactly.
- Respect setting, time, lighting, emotion.
- Style: children's book, soft watercolor, pastel, warm tones.
- Output only ONE paragraph in ENGLISH.
"""

def scene_to_visual_prompt(scene_text: str, character_sheet: str) -> str:
    message = f"""
TURKISH CHARACTER SHEET:
{character_sheet}

TURKISH SCENE:
{scene_text}

NOW OUTPUT ONLY ONE ENGLISH VISUAL PROMPT:
"""
    response = groq_client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": VISUAL_SYSTEM_PROMPT},
            {"role": "user", "content": message}
        ],
        temperature=0.4,
        max_tokens=400
    )
    return response.choices[0].message.content

# FLUX GÖRSEL ÜRETİMİ
def generate_image_from_prompt(prompt: str) -> Image.Image:
    """
    HuggingFace FLUX çıktısı hem bytes hem de PIL Image dönebildiği için
    ikisini de güvenli şekilde işleyen fonksiyon.
    """
    result = hf_image.text_to_image(
        prompt=prompt,
        width=768,
        height=768
    )

    if isinstance(result, (bytes, bytearray)):
        try:
            return Image.open(io.BytesIO(result)).convert("RGB")
        except:
            pass

    if isinstance(result, Image.Image):
        return result.convert("RGB")

    if isinstance(result, list):
        first = result[0]
        if isinstance(first, (bytes, bytearray)):
            return Image.open(io.BytesIO(first)).convert("RGB")
        if isinstance(first, Image.Image):
            return first.convert("RGB")

    raise ValueError("Unsupported image return type:", type(result))


# PIPELINE
def pipeline(sentence: str, scene_count: int):
    try:
        story = generate_story(sentence, scene_count)
        character_sheet = extract_character_sheet(story)
        scenes = extract_scenes(story)[:scene_count]

        html = f"<h2>Hikâye</h2><p>{story.replace('\n', '<br>')}</p>"
        images = []

        for i, scene in enumerate(scenes, 1):
            try:
                prompt = scene_to_visual_prompt(scene, character_sheet)
                img = generate_image_from_prompt(prompt)
                images.append(img)

                buf = io.BytesIO()
                img.save(buf, format="PNG")
                img_b64 = base64.b64encode(buf.getvalue()).decode()

                html += f"""
                <h3>Sahne {i}</h3>
                <img src="data:image/png;base64,{img_b64}" width="600"/>
                <p>{scene}</p>
                """

            except Exception as e:
                html += f"<p style='color:red;'>Görsel hatası (Sahne {i}): {e}</p>"

        return html, images

    except Exception as e:
        return f"<h3 style='color:red;'>HATA: {e}</h3>", []

# GRADIO ARAYÜZÜ (KİTAP TASARIMI)
with gr.Blocks(
    title="Türkçe Masal Kitabı",
    css="body { background:#f7efe3 }"
) as demo:

    gr.Markdown("""
    <h1 style="text-align:center; color:#5a381e;">📚 Türkçe Masal → Sahne → Görsel Kitap</h1>
    """)

    sentence_in = gr.Textbox(label="Başlangıç Cümlesi")
    scene_count_in = gr.Slider(1, 8, value=4, label="Sahne Sayısı")

    btn = gr.Button("📘 Masalı Oluştur")

    story_out = gr.HTML()
    images_out = gr.Gallery(columns=2)

    btn.click(
        pipeline,
        inputs=[sentence_in, scene_count_in],
        outputs=[story_out, images_out]
    )

demo.launch(share=True)